---
- name: Ensure tags are present on a resource
  become: False
  connection: local
  hosts: all
  tasks:
  - name: Country Tagging
    ec2_tag:
      region: us-east-1
      resource: i-082f4b2172baeab70
      state: present
      tags:
        Country: US
